name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main
    paths:
      - "resume.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Commit and push if PDF changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resume.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update PDF resume" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
